name: Publish packages

on:
  push:
    tags:
    - 'v**'

  workflow_dispatch:

jobs:
  build_python_packages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: addnab/docker-run-action@v3
      name: Build with Suse
      continue-on-error: true
      with:
        image: opensuse/leap:15.4
        options: -v ${{ github.workspace }}:/suse
        run: |
          zypper addrepo https://download.opensuse.org/repositories/openSUSE:Leap:15.4/standard/openSUSE:Leap:15.4.repo
          zypper --gpg-auto-import-keys refresh
          zypper --non-interactive install -y gcc-c++ make gcc automake autoconf libtool python3-pip python3-setuptools python3-wheel          
          zypper addrepo https://download.opensuse.org/repositories/home:smarty12:Python/RaspberryPi_Leap_15.2/home:smarty12:Python.repo
          zypper --gpg-auto-import-keys refresh
          zypper download python3-dev
          rpm -i --nodeps /var/cache/zypp/packages/home_smarty12_Python/noarch/python3-dev-0.4.0-lp152.1.4.noarch.rpm
          zypper --non-interactive install -y python3-dev
          echo "Building jans-linux-setup package"
          cd /suse/jans-linux-setup
          pip install shiv
          make zipapp
          mv jans-linux-setup.pyz jans-linux-suse-X86-64-setup.pyz
          sha256sum jans-linux-suse-X86-64-setup.pyz > jans-linux-suse-X86-64-setup.pyz.sha256sum
          cd ../jans-cli-tui
          make zipapp 
          mv config-cli-tui.pyz jans-cli-tui-linux-suse-X86-64.pyz
          sha256sum jans-cli-tui-linux-suse-X86-64.pyz > jans-cli-tui-linux-suse-X86-64.pyz.sha256sum
    # To be removed once we get SUSE build working
    - uses: addnab/docker-run-action@v3
      name: Build with CentOS7
      continue-on-error: true
      with:
        image: centos:centos7
        options: -v ${{ github.workspace }}:/centos
        run: |
          yum install python36u python36u-devel python36u-pip -y
          yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y
          curl https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz --output Python-3.7.9.tgz
          tar xzf Python-3.7.9.tgz
          cd Python-3.7.9
          ./configure --enable-optimizations
          yum install make -y
          make altinstall
          yum -y install epel-release
          curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
          python3.7 get-pip.py
          echo "Building jans-linux-setup package"
          cd /centos/jans-linux-setup
          pip install shiv
          make zipapp
          mv jans-linux-setup.pyz jans-linux-X86-64-setup.pyz
          sha256sum jans-linux-X86-64-setup.pyz > jans-linux-X86-64-setup.pyz.sha256sum
          cd ../jans-cli-tui
          make zipapp 
          mv config-cli-tui.pyz jans-cli-tui-linux-centos-X86-64.pyz
          sha256sum jans-cli-tui-linux-centos-X86-64.pyz > jans-cli-tui-linux-centos-X86-64.pyz.sha256sum
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
    - name: Build with Ubuntu
      continue-on-error: true
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 build-essential ca-certificates dbus systemd iproute2 gpg python3-pip python3-dev libpq-dev gcc
        python3 -m pip install --upgrade pip
        pip3 install shiv wheel setuptools
        echo "Building jans-linux-setup package"
        sudo chown -R runner:docker /home/runner/work/jans/jans
        cd jans-linux-setup
        make zipapp || echo "Creating linux setup failed for ubuntu"
        mv jans-linux-setup.pyz jans-linux-ubuntu-X86-64-setup.pyz || echo "Failed"
        sha256sum jans-linux-ubuntu-X86-64-setup.pyz > jans-linux-ubuntu-X86-64-setup.pyz.sha256sum || echo "Failed"
        echo "Building jans-cli-tui package"
        cd ../jans-cli-tui
        make zipapp 
        mv config-cli-tui.pyz jans-cli-tui-linux-ubuntu-X86-64.pyz
        sha256sum jans-cli-tui-linux-ubuntu-X86-64.pyz > jans-cli-tui-linux-ubuntu-X86-64.pyz.sha256sum
    - uses: actions/cache@v3
      id: cache-installers
      with:
        path: |
          ${{github.workspace}}/jans-linux-setup/jans-linux-X86-64-setup.pyz
          ${{github.workspace}}/jans-linux-setup/jans-linux-X86-64-setup.pyz.sha256sum
          ${{github.workspace}}/jans-linux-setup/jans-linux-suse-X86-64-setup.pyz
          ${{github.workspace}}/jans-linux-setup/jans-linux-suse-X86-64-setup.pyz.sha256sum
          ${{github.workspace}}/jans-linux-setup/jans-linux-ubuntu-X86-64-setup.pyz
          ${{github.workspace}}/jans-linux-setup/jans-linux-ubuntu-X86-64-setup.pyz.sha256sum
          ${{github.workspace}}/jans-cli-tui/jans-cli-tui-linux-X86-64.pyz
          ${{github.workspace}}/jans-cli-tui/jans-cli-tui-linux-X86-64.pyz.sha256sum
          ${{github.workspace}}/jans-cli-tui/jans-cli-tui-linux-suse-X86-64.pyz
          ${{github.workspace}}/jans-cli-tui/jans-cli-tui-linux-suse-X86-64.pyz.sha256sum
          ${{github.workspace}}/jans-cli-tui/jans-cli-tui-linux-ubuntu-X86-64.pyz
          ${{github.workspace}}/jans-cli-tui/jans-cli-tui-linux-ubuntu-X86-64.pyz.sha256sum
        key: ${{ github.sha }}

