name: Publish packages

on:
  push:
    tags:
    - 'v**'

  workflow_dispatch:

jobs:
  build_python_packages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: addnab/docker-run-action@v3
      name: Build with Suse
      continue-on-error: true
      with:
        image: opensuse/leap:15.4
        options: -v ${{ github.workspace }}:/suse
        run: |
          zypper addrepo https://download.opensuse.org/repositories/openSUSE:Leap:15.4/standard/openSUSE:Leap:15.4.repo
          zypper --gpg-auto-import-keys refresh
          zypper --non-interactive install -y gcc-c++ make gcc automake autoconf libtool python3-pip python3-setuptools python3-wheel          
          zypper addrepo https://download.opensuse.org/repositories/home:smarty12:Python/RaspberryPi_Leap_15.2/home:smarty12:Python.repo
          zypper --gpg-auto-import-keys refresh
          zypper download python3-dev
          rpm -i --nodeps /var/cache/zypp/packages/home_smarty12_Python/noarch/python3-dev-0.4.0-lp152.1.4.noarch.rpm
          zypper --non-interactive install -y python3
          zypper --non-interactive install -y python3-devel
          echo "Building jans-linux-setup package"
          cd /suse/jans-linux-setup
          pip install shiv
          make zipapp
          mv jans-linux-setup.pyz jans-linux-suse-X86-64-setup.pyz
          sha256sum jans-linux-suse-X86-64-setup.pyz > jans-linux-suse-X86-64-setup.pyz.sha256sum
          cd ../jans-cli-tui
          make zipapp 
          mv config-cli-tui.pyz jans-cli-tui-linux-suse-X86-64.pyz
          sha256sum jans-cli-tui-linux-suse-X86-64.pyz > jans-cli-tui-linux-suse-X86-64.pyz.sha256sum

